# Configuration for pipeline

# input files
extended_gene: data/extended_spike_KP.3.1.1.fa
reference_gene: data/reference_spike.fa
human_codon_freqs: data/human_codon_freq.csv

# URL of GISAID mutation count data on CoVsurver:
alignment_count_url: https://mendel.bii.a-star.edu.sg/METHODS/corona/current/MUTATIONS/hCoV-19_Human_2019_WuhanWIV04/hcov19_Spike_mutations_table.html

# URLs of UShER tree, GTF, and reference sequence
usher_mat: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/public-latest.all.masked.pb.gz
usher_gtf: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/bigZips/genes/ncbiGenes.gtf.gz
usher_fasta: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/bigZips/wuhCor1.fa.gz

# "recent" Nextstrain clades for analysis on UShER tree
# Note clade names here have to exactly match how they are defined in the UShER tree;
# if you are not sure how they are named use
# "matUtils summary -i results/usher/mat.pb.gz -c clades.tsv"
# and then look at the clade names in "clades.tsv"
usher_recent_clades:
  - 23I (BA.2.86)  # BA.2.86
  - JN.1           # JN.1

# Keep mutations with >= this many counts for each threshold.
mutation_retain_thresholds:
  GISAID_count: 50
  UShER_count: 10
  UShER_recent_count: 1

# Saturating substitution mutagenesis at sites with >= this many total
# substitution counts:
site_saturation_threshold:
  UShER_count: 2500
  UShER_recent_count: 50

# Regardless of counts, only include deletion mutations in these sites
# specifically listed under `mutations_to_include`. Specify a list of inclusive
# site ranges in reference numbering
sites_to_allow_deletions:
  - [13, 304]  # NTD as defined at https://www.ncbi.nlm.nih.gov/protein/1796318598
  - [331, 354]
  - [434, 508]

# include these mutations regardless of counts, in reference numbering
mutations_to_include:
  - 19-
  - 21-
  - 211-
  - 342-
  - 343-
  - 344-
  - 345-
  - 346-
  - 347-
  - 348-
  - 349-
  - 444-
  - 445-
  - 446-
  - 447-
  - 448-
  - 449-
  - 483-
  - 484-
  - 485-
  - 486-

# do we saturate mutagenesis of substitutions at sites that differ from reference?
saturate_diffs_from_reference: true

# do we include STOP codons
include_STOP: false

# saturating mutagenesis of substitutions at these sites, in reference numbering
sites_to_saturate:
  # sature the whole RBD
  - [331, 531]
  # sites present in various JN.1* descendants based on Bette Korber SAVES updates
  - 18
  - 19
  - 20
  - 21
  - 50
  - 59
  - 67
  - 142
  - 146
  - 147
  - 183
  - 190
  - 212
  - 245
  - 246
  - 249
  - 246
  - 572
  - 783
  - 852
  - 942
  - 1086
  - 1087
  - 1266
  - 1229

# insertion sites in KP.3.1.1
insertion_sites: data/insertion_sites.csv

# output files
sequential_to_reference: data/sequential_to_reference.csv
alignment_counts: results/alignment_counts.csv
usher_mut_counts: results/usher/mut_counts.csv
usher_recent_mut_counts: results/usher/recent_mut_counts.csv
mutation_stats: results/mutation_stats.csv
mutations_to_make_chart: results/mutations_to_make.html
mutation_design_classification: results/mutation_design_classification.csv
targeted_mutations: results/targeted_mutations.csv
saturated_sites: results/saturated_sites.csv
