# Configuration for pipeline

# Spike coding sequence of the variant being used as the DMS parent
variant_spike: data/variant_spike.fa

# Pango lineage of the variant being used as the DMS parent; sequence
# is checked against the Pango JSON
variant_lineage: KP.3.1.1

# Accession of the reference (Wuhan-Hu-1) spike protein, which
# defines the reference numbering scheme.
ref_spike_accession: QHD43416

# The variant in the experiments is truncated starting at this position
# in reference spike numbering (due to the C-terminal tail deletion)
ref_cterm_truncation_start: 1253

# JSON file with Pango lineages as defined by Cornelius Roemer
pango_lineages_json: https://raw.githubusercontent.com/corneliusroemer/pango-sequences/main/data/pango-consensus-sequences_summary.json

# URL of GISAID mutation count data on CoVsurver:
alignment_count_url: https://mendel.bii.a-star.edu.sg/METHODS/corona/current/MUTATIONS/hCoV-19_Human_2019_WuhanWIV04/hcov19_Spike_mutations_table.html

# URLs of UShER tree, GTF, and reference sequence
usher_mat: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/public-latest.all.masked.pb.gz
usher_gtf: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/bigZips/genes/ncbiGenes.gtf.gz
usher_fasta: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/bigZips/wuhCor1.fa.gz

# "recent" Nextstrain clades for analysis on UShER tree
# Clade names here have to exactly match how they are defined in the UShER tree;
# if you are not sure how they are named use then look at the
# "results/usher/clade_count.tsv" file created by the pipeline.
usher_recent_clades:
  - 23I (BA.2.86)
  - 24A (JN.1)
  - 24B (JN.1.11.1)
  - 24C (KP.3)

# Keep mutations with >= this many counts for each category
mutation_retain_thresholds:
  UShER_count: 10
  UShER_recent_count: 1
  in_pango_lineage: 1
  alignment_count: 50

# Saturate mutations (including deletions) at sites with >= this many counts across
# all mutations.
site_saturation_thresholds:
  UShER_count: 2500
  UShER_recent_count: 50
  in_pango_lineage: 2
  mutated_from_reference: 1

# do we include STOP codons when they meet other criteria
include_stop: false

# Only include deletion mutations in these sites (reference numbering) regardless of counts
# Specify a list of inclusive site ranges in reference numbering
sites_to_allow_deletions:
  - [13, 304]  # NTD as defined at https://www.ncbi.nlm.nih.gov/protein/1796318598
  - [331, 354]
  - [434, 508]

# include these mutations regardless of counts, in reference numbering, as <site><mutant_aa>
mutations_to_include:
  - 19-
  - 21-
  - 342-
  - 343-
  - 344-
  - 345-
  - 346-
  - 347-
  - 348-
  - 349-
  - 444-
  - 445-
  - 446-
  - 447-
  - 448-
  - 449-
  - 484-
  - 485-
  - 486-

# Saturating mutagenesis of substitutions at these sites, in reference numbering
# List either individual sites or ranges of sites.
sites_to_saturate:
  - [331, 531]  # RBD
  - 16a
  - 16b
  - 16c
  - 16d
  - 18
  - 19
  - 20
  - 21
  - 50
  - 59
  - 67
  - 142
  - 146
  - 147
  - 183
  - 190
  - 212
  - 245
  - 246
  - 249
  - 246
  - 572
  - 783
  - 852
  - 942
  - 1086
  - 1087
  - 1229
