name: spike_library_design
channels:
  - conda-forge
  - bioconda

dependencies:
  - altair=5.4
  - biopython=1.84
  - entrez-direct=22.4
  - jupyterlab
  - mafft=7.525
  - mamba
  - pandas=2.2
  - pip
  - pyarrow
  - python=3.12
  - pyyaml=6.0
  - requests=2.32
  - snakemake=8.18
