name: spike_library_design
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - biopython=1.81
  - entrez-direct=13.9
  - notebook=6.4.12
  - jupyterlab
  - jupyter_nbextensions_configurator
  - jupyter_contrib_nbextensions
  - mafft=7.515
  - mamba
  - pandas=1.5
  - pip
  - python=3.10
  - pyyaml=6.0
  - requests=2.28
  - snakemake=7.24
  - usher
  - pip:
    - altair==5.0.0rc1
    - traitlets==5.9.0
